import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const q=s=>document.querySelector(s),container=q('#viewer'),toolButtons=[...document.querySelectorAll('.tool')],contextPanel=q('#context-panel'),panelKicker=q('#panel-kicker'),panelTitle=q('#panel-title'),panelContent=q('#panel-content'),walkControl=q('#walk-control'),joystick=q('#joystick'),joystickKnob=q('#joystick-knob'),measureStatus=q('#measure-status'),interactionHint=q('#interaction-hint');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xebece8);scene.fog=new THREE.Fog(0xebece8,18,42);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.05,100);camera.position.set(9,6.4,10.5);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.target.set(0,1.25,0);controls.minDistance=3;controls.maxDistance=22;controls.maxPolarAngle=Math.PI*.48;controls.update();
scene.add(new THREE.HemisphereLight(0xffffff,0xb9b9b2,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.6);sun.position.set(7,11,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-11,right:11,top:11,bottom:-11});scene.add(sun);
const architecture=new THREE.Group();scene.add(architecture);const matte=(color,roughness=.82)=>new THREE.MeshStandardMaterial({color,roughness}),white=matte(0xf7f6f2),warmWhite=matte(0xe9e5dc),glass=new THREE.MeshPhysicalMaterial({color:0xcbd8d8,transparent:true,opacity:.28,roughness:.15,side:THREE.DoubleSide}),green=matte(0x536c5d,.7),charcoal=matte(0x3f4642,.75);
function box(name,size,position,material,cast=true){const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),material);mesh.name=name;mesh.position.set(...position);mesh.castShadow=cast;mesh.receiveShadow=true;architecture.add(mesh);return mesh}
box('Floor',[16,.18,10],[0,-.09,0],warmWhite,false);box('Rear wall',[16,3.4,.16],[0,1.7,-5],white,false);box('Side wall',[.16,3.4,10],[-8,1.7,0],white,false);box('Meeting room glass',[.08,2.75,5.2],[2.7,1.38,-2.35],glass,false);box('Meeting table',[3.5,.12,1.35],[5.15,.76,-2.45],matte(0xb79d78));for(const x of [3.85,5.15,6.45])for(const z of [-1.45,-3.45])box('Meeting chair',[.55,.72,.55],[x,.36,z],charcoal);box('Reception desk',[3.2,1.05,.75],[-4.7,.53,-2.75],white);box('Feature wall',[3.8,2.5,.22],[-4.7,1.25,-4.82],green,false);for(const x of [-2.5,-.8,.9]){box('Worktable',[1.3,.08,2.6],[x,.72,1.2],matte(0xc2ad8f));box('Desk base',[.08,.7,2.25],[x,.35,1.2],charcoal)}box('Lounge sofa',[3.3,.68,1],[4.8,.34,2.85],matte(0xb8c1bd));box('Coffee table',[1.4,.34,.7],[4.8,.17,1.85],matte(0x59605b));for(const z of [-3.7,0,3.7])box('Window mullion',[.12,3.1,.12],[7.85,1.55,z],charcoal,false);const grid=new THREE.GridHelper(30,30,0xcbd0cb,0xd9ddd8);grid.position.y=.012;scene.add(grid);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),markerGroup=new THREE.Group();scene.add(markerGroup);let activeTool='orbit',transition,measurePoints=[],joystickPointer,previousTime=performance.now();const walkVector=new THREE.Vector2();
const overview=`<div class="mode-tabs"><button class="active">Interactive 3D</button><button>Render gallery</button></div><div class="panel-list"><button class="panel-option active" data-view="perspective"><small>01</small><b>Whole workspace</b><i>↗</i></button><button class="panel-option" data-view="entrance"><small>02</small><b>Entrance</b><i>↗</i></button><button class="panel-option" data-view="top"><small>03</small><b>Floor plan</b><i>↗</i></button></div><div class="project-stats"><div><strong>1,583</strong><small>sq ft · Floor</small></div><div><strong>3</strong><small>Saved views</small></div><div><strong>3.4</strong><small>m · Ceiling</small></div></div><p class="panel-footnote">Placeholder geometry for reviewing the platform interface. Your new SketchUp GLB will replace it later.</p>`;
const panels={views:{title:'Explore the space.',content:overview},material:{title:'Material',content:`<p class="panel-message"><strong>Material controls are reserved.</strong>The final model will use calibrated PBR values, correct texture scale and restrained reflections after the UI is approved.</p>`},light:{title:'Light',content:`<p class="panel-message"><strong>Neutral studio lighting preview.</strong>The placeholder currently uses soft global fill and one directional key light only. GI, AO and IES remain excluded from this phase.</p>`},layers:{title:'Layers',content:`<div class="toggle-row"><span>Placeholder interior</span><button class="switch" aria-label="Placeholder interior visible"></button></div><p class="panel-message">SketchUp layer controls will connect to the new GLB structure later.</p>`},ai:{title:'AI Visualize',content:`<p class="panel-message"><strong>Coming in a later phase.</strong>AI rendering is not connected in this platform review.</p>`}};
function clearMeasurement(){measurePoints=[];markerGroup.clear();if(activeTool==='measure')measureStatus.textContent='Tap two surfaces to measure'}
function bindViews(){panelContent.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>moveToView(b.dataset.view)))}
function openPanel(name){const panel=panels[name];if(!panel)return;panelKicker.textContent=name==='ai'?'FUTURE TOOL':'THE SPACE';panelTitle.textContent=panel.title;panelContent.innerHTML=panel.content;contextPanel.hidden=false;bindViews()}
function setActiveTool(name){activeTool=name;toolButtons.forEach(b=>{const active=b.dataset.tool===name;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});controls.enabled=name!=='walk'&&name!=='measure';walkControl.hidden=name!=='walk';measureStatus.hidden=name!=='measure';interactionHint.textContent=name==='walk'?'Use the controller to walk · Drag to look':name==='measure'?'Select two points in the model':'Drag to orbit · Pinch or scroll to zoom';if(name!=='measure')clearMeasurement();if(panels[name])openPanel(name);else contextPanel.hidden=true}
function moveToView(name){const views={perspective:[[9,6.4,10.5],[0,1.25,0]],entrance:[[-1,1.65,8],[0,1.35,0]],top:[[0,17,.01],[0,0,0]]},view=views[name];if(!view)return;transition={start:performance.now(),from:camera.position.clone(),fromTarget:controls.target.clone(),to:new THREE.Vector3(...view[0]),target:new THREE.Vector3(...view[1])};panelContent.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function measure(event){if(activeTool!=='measure')return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObject(architecture,true)[0];if(!hit)return;if(measurePoints.length===2)clearMeasurement();measurePoints.push(hit.point.clone());const marker=new THREE.Mesh(new THREE.SphereGeometry(.07,16,16),new THREE.MeshBasicMaterial({color:0x284f3d}));marker.position.copy(hit.point);markerGroup.add(marker);if(measurePoints.length===1)measureStatus.textContent='Tap the second point';if(measurePoints.length===2){markerGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(measurePoints),new THREE.LineBasicMaterial({color:0x284f3d})));measureStatus.textContent=`${measurePoints[0].distanceTo(measurePoints[1]).toFixed(2)} m`}}
toolButtons.forEach(button=>button.addEventListener('click',async()=>{const name=button.dataset.tool;if(name==='fullscreen'){if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();return}setActiveTool(name)}));q('#close-panel').addEventListener('click',()=>setActiveTool('orbit'));renderer.domElement.addEventListener('click',measure);renderer.domElement.addEventListener('pointerdown',()=>document.body.classList.add('dragging'));window.addEventListener('pointerup',()=>document.body.classList.remove('dragging'));
joystick.addEventListener('pointerdown',e=>{joystickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId)});joystick.addEventListener('pointermove',e=>{if(joystickPointer!==e.pointerId)return;const r=joystick.getBoundingClientRect();walkVector.set((e.clientX-r.left)/r.width*2-1,(e.clientY-r.top)/r.height*2-1).clampLength(0,1);joystickKnob.style.transform=`translate(calc(-50% + ${walkVector.x*27}px),calc(-50% + ${walkVector.y*27}px))`});joystick.addEventListener('pointerup',()=>{joystickPointer=undefined;walkVector.set(0,0);joystickKnob.style.transform='translate(-50%,-50%)'});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
bindViews();
renderer.setAnimationLoop(time=>{const dt=Math.min((time-previousTime)/1000,.05);previousTime=time;if(transition){const p=Math.min((time-transition.start)/750,1),e=1-(1-p)**3;camera.position.lerpVectors(transition.from,transition.to,e);controls.target.lerpVectors(transition.fromTarget,transition.target,e);if(p===1)transition=undefined}if(activeTool==='walk'){const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,camera.up).normalize();camera.position.addScaledVector(forward,-walkVector.y*3*dt);camera.position.addScaledVector(right,walkVector.x*3*dt);camera.position.y=1.6;controls.target.copy(camera.position).add(forward)}controls.update();renderer.render(scene,camera)});
